#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export OPENFGA_IMAGE_TAG="latest"
export OPENFGA_IMAGE="openfga/openfga:$OPENFGA_IMAGE_TAG"
