name: Build
on:
  push:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go mod download
      - name: Build
        run: make build
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: config install
          check_together: "yes"
          ignore_names: .editorconfig
          ignore_paths: ./src ./.idea
